name: soberoctobr-backend
services:
  - name: api
    environment_slug: python
    github:
      repo: mindfulent/soberoctobr-backend
      branch: master
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: bash start-production.sh
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_REDIRECT_URI
        scope: RUN_TIME
        type: SECRET
      - key: API_BASE_URL
        scope: RUN_TIME
      - key: FRONTEND_URL
        scope: RUN_TIME
      - key: CORS_ORIGINS
        scope: RUN_TIME
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "10080"
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
      - key: ALGORITHM
        scope: RUN_TIME
        value: "HS256"

databases:
  - name: soberoctobr-db
    engine: PG
    production: false
    version: "16"
