"""Add icon field to habits table

Revision ID: 9d0db9fcbe43
Revises: 115b2f20f97e
Create Date: 2025-10-04 19:46:54.543638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0db9fcbe43'
down_revision: Union[str, None] = '115b2f20f97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'icon')
    # ### end Alembic commands ###
